# Generated by Django 5.1.2 on 2024-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rfid', '0002_alter_rfid_id_esp32_alter_rfid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
